<?php

namespace Database\Seeders;

use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use App\Models\AuditLog;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // User::factory(10)->create();

        // 1. Usuários (users)
        DB::table('users')->insert([
            // Administradores
            [
                'email' => 'admin@eduangola.ao',
                'password_hash' => Hash::make('password123'),
                'user_type' => 'admin',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'email' => 'maria.admin@eduangola.ao',
                'password_hash' => Hash::make('password123'),
                'user_type' => 'admin',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'email' => 'joao.admin@eduangola.ao',
                'password_hash' => Hash::make('password123'),
                'user_type' => 'admin',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            // Usuários Instituição (ajustado para user_type 'admin')
            [
                'email' => 'instituicao@uan.ao',
                'password_hash' => Hash::make('password123'),
                'user_type' => 'admin',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'email' => 'instituicao@ucan.ao',
                'password_hash' => Hash::make('password123'),
                'user_type' => 'admin',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            // Professores
            [
                'email' => 'maria.santos@eduangola.ao',
                'password_hash' => Hash::make('password123'),
                'user_type' => 'teacher',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'email' => 'joao.lima@eduangola.ao',
                'password_hash' => Hash::make('password123'),
                'user_type' => 'teacher',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'email' => 'ana.costa@eduangola.ao',
                'password_hash' => Hash::make('password123'),
                'user_type' => 'teacher',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'email' => 'carlos.santos@eduangola.ao',
                'password_hash' => Hash::make('password123'),
                'user_type' => 'teacher',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'email' => 'luisa.fernandes@eduangola.ao',
                'password_hash' => Hash::make('password123'),
                'user_type' => 'teacher',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            // Alunos
            [
                'email' => 'pedro.santos@estudante.ao',
                'password_hash' => Hash::make('password123'),
                'user_type' => 'student',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'email' => 'ana.silva@estudante.ao',
                'password_hash' => Hash::make('password123'),
                'user_type' => 'student',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'email' => 'joao.costa@estudante.ao',
                'password_hash' => Hash::make('password123'),
                'user_type' => 'student',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'email' => 'maria.lima@estudante.ao',
                'password_hash' => Hash::make('password123'),
                'user_type' => 'student',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'email' => 'carlos.fernandes@estudante.ao',
                'password_hash' => Hash::make('password123'),
                'user_type' => 'student',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'email' => 'beatriz.santos@estudante.ao',
                'password_hash' => Hash::make('password123'),
                'user_type' => 'student',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'email' => 'rafael.costa@estudante.ao',
                'password_hash' => Hash::make('password123'),
                'user_type' => 'student',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'email' => 'sofia.lima@estudante.ao',
                'password_hash' => Hash::make('password123'),
                'user_type' => 'student',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'email' => 'miguel.silva@estudante.ao',
                'password_hash' => Hash::make('password123'),
                'user_type' => 'student',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
        ]);

        // 2. Administradores (admins)
        DB::table('admins')->insert([
            [
                'user_id' => 1,
                'first_name' => 'Admin',
                'last_name' => 'Sistema',
                'phone' => '+244 923 456 789',
                'role' => 'Super Administrador',
                'permissions' => '{"users": true, "academic": true, "reports": true, "system": true, "communication": true}',
                'profile_picture' => null,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'first_name' => 'Maria Fernanda',
                'last_name' => 'Costa',
                'phone' => '+244 924 567 890',
                'role' => 'Administrador Acadêmico',
                'permissions' => '{"users": true, "academic": true, "reports": true, "system": false, "communication": true}',
                'profile_picture' => null,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'first_name' => 'João Carlos',
                'last_name' => 'Silva',
                'phone' => '+244 925 678 901',
                'role' => 'Administrador de Sistema',
                'permissions' => '{"users": false, "academic": false, "reports": true, "system": true, "communication": false}',
                'profile_picture' => null,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'first_name' => 'Universidade',
                'last_name' => 'Agostinho Neto',
                'phone' => '+244 222 334 455',
                'role' => 'Administrador Institucional',
                'permissions' => '{"users": true, "academic": true, "reports": true, "system": false, "communication": true}',
                'profile_picture' => null,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'first_name' => 'Universidade',
                'last_name' => 'Católica',
                'phone' => '+244 222 445 566',
                'role' => 'Administrador Institucional',
                'permissions' => '{"users": true, "academic": true, "reports": true, "system": false, "communication": true}',
                'profile_picture' => null,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
        ]);

        // 3. Professores (teachers)
        DB::table('teachers')->insert([
            [
                'user_id' => 6,
                'teacher_number' => 'PROF001',
                'first_name' => 'Maria Santos',
                'last_name' => 'Silva',
                'date_of_birth' => '1985-03-15',
                'gender' => 'F',
                'phone' => '+244 923 456 789',
                'address' => null,
                'hire_date' => '2020-03-15',
                'qualification' => 'Mestrado',
                'specialization' => 'Matemática',
                'experience_years' => 8,
                'salary' => 150000.00,
                'profile_picture' => null,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'user_id' => 7,
                'teacher_number' => 'PROF002',
                'first_name' => 'João Carlos',
                'last_name' => 'Lima',
                'date_of_birth' => '1980-08-20',
                'gender' => 'M',
                'phone' => '+244 924 567 890',
                'address' => null,
                'hire_date' => '2018-08-20',
                'qualification' => 'Doutorado',
                'specialization' => 'Medicina',
                'experience_years' => 12,
                'salary' => 200000.00,
                'profile_picture' => null,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'user_id' => 8,
                'teacher_number' => 'PROF003',
                'first_name' => 'Ana Pereira',
                'last_name' => 'Costa',
                'date_of_birth' => '1990-01-10',
                'gender' => 'F',
                'phone' => '+244 925 678 901',
                'address' => null,
                'hire_date' => '2022-01-10',
                'qualification' => 'Licenciatura',
                'specialization' => 'História',
                'experience_years' => 5,
                'salary' => 120000.00,
                'profile_picture' => null,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'user_id' => 9,
                'teacher_number' => 'PROF004',
                'first_name' => 'Carlos Manuel',
                'last_name' => 'Santos',
                'date_of_birth' => '1982-05-25',
                'gender' => 'M',
                'phone' => '+244 926 789 012',
                'address' => null,
                'hire_date' => '2019-02-01',
                'qualification' => 'Mestrado',
                'specialization' => 'Informática',
                'experience_years' => 10,
                'salary' => 160000.00,
                'profile_picture' => null,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'user_id' => 10,
                'teacher_number' => 'PROF005',
                'first_name' => 'Luisa Maria',
                'last_name' => 'Fernandes',
                'date_of_birth' => '1988-11-30',
                'gender' => 'F',
                'phone' => '+244 927 890 123',
                'address' => null,
                'hire_date' => '2015-09-01',
                'qualification' => 'Doutorado',
                'specialization' => 'Psicologia',
                'experience_years' => 15,
                'salary' => 180000.00,
                'profile_picture' => null,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
        ]);

        // 4. Alunos (students)
        DB::table('students')->insert([
            // Universitários
            [
                'user_id' => 11,
                'student_number' => 'UNI2024001',
                'first_name' => 'Pedro Miguel',
                'last_name' => 'Santos',
                'date_of_birth' => '2002-05-15',
                'gender' => 'M',
                'phone' => '+244 930 123 456',
                'address' => null,
                'enrollment_date' => '2024-02-01',
                'parent_name' => 'José Santos',
                'parent_phone' => '+244 920 123 456',
                'parent_email' => null,
                'emergency_contact' => null,
                'emergency_phone' => null,
                'profile_picture' => null,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'user_id' => 12,
                'student_number' => 'UNI2024002',
                'first_name' => 'Ana Clara',
                'last_name' => 'Silva',
                'date_of_birth' => '2001-08-20',
                'gender' => 'F',
                'phone' => '+244 931 234 567',
                'address' => null,
                'enrollment_date' => '2024-02-01',
                'parent_name' => 'Manuel Silva',
                'parent_phone' => '+244 921 234 567',
                'parent_email' => null,
                'emergency_contact' => null,
                'emergency_phone' => null,
                'profile_picture' => null,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'user_id' => 13,
                'student_number' => 'UNI2024003',
                'first_name' => 'João Paulo',
                'last_name' => 'Costa',
                'date_of_birth' => '2003-01-10',
                'gender' => 'M',
                'phone' => '+244 932 345 678',
                'address' => null,
                'enrollment_date' => '2024-02-01',
                'parent_name' => 'António Costa',
                'parent_phone' => '+244 922 345 678',
                'parent_email' => null,
                'emergency_contact' => null,
                'emergency_phone' => null,
                'profile_picture' => null,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'user_id' => 14,
                'student_number' => 'UNI2024004',
                'first_name' => 'Maria Eduarda',
                'last_name' => 'Lima',
                'date_of_birth' => '2002-11-25',
                'gender' => 'F',
                'phone' => '+244 933 456 789',
                'address' => null,
                'enrollment_date' => '2024-02-01',
                'parent_name' => 'Francisco Lima',
                'parent_phone' => '+244 923 456 789',
                'parent_email' => null,
                'emergency_contact' => null,
                'emergency_phone' => null,
                'profile_picture' => null,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            // Ensino Médio
            [
                'user_id' => 15,
                'student_number' => 'MED2024001',
                'first_name' => 'Carlos Eduardo',
                'last_name' => 'Fernandes',
                'date_of_birth' => '2007-03-12',
                'gender' => 'M',
                'phone' => '+244 934 567 890',
                'address' => null,
                'enrollment_date' => '2024-02-01',
                'parent_name' => 'Roberto Fernandes',
                'parent_phone' => '+244 924 567 890',
                'parent_email' => null,
                'emergency_contact' => null,
                'emergency_phone' => null,
                'profile_picture' => null,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'user_id' => 16,
                'student_number' => 'MED2024002',
                'first_name' => 'Beatriz Maria',
                'last_name' => 'Santos',
                'date_of_birth' => '2006-09-18',
                'gender' => 'F',
                'phone' => '+244 935 678 901',
                'address' => null,
                'enrollment_date' => '2024-02-01',
                'parent_name' => 'Paulo Santos',
                'parent_phone' => '+244 925 678 901',
                'parent_email' => null,
                'emergency_contact' => null,
                'emergency_phone' => null,
                'profile_picture' => null,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'user_id' => 17,
                'student_number' => 'MED2024003',
                'first_name' => 'Rafael José',
                'last_name' => 'Costa',
                'date_of_birth' => '2007-07-22',
                'gender' => 'M',
                'phone' => '+244 936 789 012',
                'address' => null,
                'enrollment_date' => '2024-02-01',
                'parent_name' => 'Joaquim Costa',
                'parent_phone' => '+244 926 789 012',
                'parent_email' => null,
                'emergency_contact' => null,
                'emergency_phone' => null,
                'profile_picture' => null,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            // Ensino Primário
            [
                'user_id' => 18,
                'student_number' => 'PRI2024001',
                'first_name' => 'Sofia Isabel',
                'last_name' => 'Lima',
                'date_of_birth' => '2012-04-08',
                'gender' => 'F',
                'phone' => '+244 937 890 123',
                'address' => null,
                'enrollment_date' => '2024-02-01',
                'parent_name' => 'Fernando Lima',
                'parent_phone' => '+244 927 890 123',
                'parent_email' => null,
                'emergency_contact' => null,
                'emergency_phone' => null,
                'profile_picture' => null,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'user_id' => 19,
                'student_number' => 'PRI2024002',
                'first_name' => 'Miguel Ângelo',
                'last_name' => 'Silva',
                'date_of_birth' => '2013-12-15',
                'gender' => 'M',
                'phone' => '+244 938 901 234',
                'address' => null,
                'enrollment_date' => '2024-02-01',
                'parent_name' => 'Alberto Silva',
                'parent_phone' => '+244 928 901 234',
                'parent_email' => null,
                'emergency_contact' => null,
                'emergency_phone' => null,
                'profile_picture' => null,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
        ]);

        // 5. Escolas (schools)
        DB::table('schools')->insert([
            [
                'name' => 'Universidade Agostinho Neto',
                'code' => 'UAN',
                'type' => 'Universidade',
                'address' => 'Luanda, Ingombota',
                'phone' => '+244 222 334 455',
                'email' => 'info@uan.ao',
                'established_date' => '1962-12-01',
                'description' => 'Principal universidade pública de Angola',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'name' => 'Universidade Católica de Angola',
                'code' => 'UCAN',
                'type' => 'Universidade',
                'address' => 'Luanda, Maianga',
                'phone' => '+244 222 445 566',
                'email' => 'info@ucan.ao',
                'established_date' => '1997-08-15',
                'description' => 'Universidade privada católica de referência',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'name' => 'Universidade Jean Piaget',
                'code' => 'UJP',
                'type' => 'Universidade',
                'address' => 'Luanda, Talatona',
                'phone' => '+244 222 556 677',
                'email' => 'info@ujp.ao',
                'established_date' => '2001-03-20',
                'description' => 'Universidade privada internacional',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'name' => 'Universidade Metodista de Angola',
                'code' => 'UMA',
                'type' => 'Universidade',
                'address' => 'Luanda, Viana',
                'phone' => '+244 222 667 788',
                'email' => 'info@uma.ao',
                'established_date' => '2003-09-15',
                'description' => 'Universidade metodista',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'name' => 'Escola Central de Luanda',
                'code' => 'ECL',
                'type' => 'Ensino Médio',
                'address' => 'Luanda, Centro',
                'phone' => '+244 222 778 899',
                'email' => 'info@ecl.ao',
                'established_date' => '1975-09-10',
                'description' => 'Escola secundária de referência em Luanda',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'name' => 'Escola do Kilamba',
                'code' => 'EK',
                'type' => 'Ensino Médio',
                'address' => 'Luanda, Kilamba',
                'phone' => '+244 222 889 900',
                'email' => 'info@ek.ao',
                'established_date' => '2010-02-20',
                'description' => 'Escola secundária moderna no Kilamba',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'name' => 'Escola da Maianga',
                'code' => 'EM',
                'type' => 'Ensino Médio',
                'address' => 'Luanda, Maianga',
                'phone' => '+244 222 990 011',
                'email' => 'info@em.ao',
                'established_date' => '1980-05-15',
                'description' => 'Escola secundária na Maianga',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'name' => 'Escola Primária do Kilamba',
                'code' => 'EPK',
                'type' => 'Ensino Primário',
                'address' => 'Luanda, Kilamba',
                'phone' => '+244 222 001 122',
                'email' => 'info@epk.ao',
                'established_date' => '2010-02-20',
                'description' => 'Escola primária moderna no Kilamba',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
        ]);

        // 6. Cursos Universitários (courses)
        DB::table('courses')->insert([
            [
                'name' => 'Engenharia Informática',
                'code' => 'EI',
                'description' => 'Curso de formação em desenvolvimento de software e sistemas',
                'duration_years' => 5,
                'total_credits' => 300,
                'school_id' => 1,
                'department' => 'Engenharia',
                'degree_type' => 'Licenciatura',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'name' => 'Medicina',
                'code' => 'MED',
                'description' => 'Curso de formação médica geral',
                'duration_years' => 6,
                'total_credits' => 360,
                'school_id' => 2,
                'department' => 'Ciências da Saúde',
                'degree_type' => 'Licenciatura',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'name' => 'Direito',
                'code' => 'DIR',
                'description' => 'Curso de formação jurídica',
                'duration_years' => 5,
                'total_credits' => 300,
                'school_id' => 2,
                'department' => 'Ciências Sociais',
                'degree_type' => 'Licenciatura',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'name' => 'Economia',
                'code' => 'ECO',
                'description' => 'Curso de formação em ciências econômicas',
                'duration_years' => 4,
                'total_credits' => 240,
                'school_id' => 1,
                'department' => 'Ciências Sociais',
                'degree_type' => 'Licenciatura',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'name' => 'Arquitetura',
                'code' => 'ARQ',
                'description' => 'Curso de formação em arquitetura e urbanismo',
                'duration_years' => 5,
                'total_credits' => 300,
                'school_id' => 3,
                'department' => 'Arquitetura',
                'degree_type' => 'Licenciatura',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'name' => 'Psicologia',
                'code' => 'PSI',
                'description' => 'Curso de formação em psicologia',
                'duration_years' => 5,
                'total_credits' => 300,
                'school_id' => 2,
                'department' => 'Ciências Humanas',
                'degree_type' => 'Licenciatura',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
        ]);

        // 7. Disciplinas (subjects)
        DB::table('subjects')->insert([
            // Disciplinas Universitárias - Engenharia Informática (sem pré-requisitos)
            [
                'name' => 'Matemática I',
                'course_id' => 1,
                'code' => 'MAT101',
                'description' => 'Fundamentos de matemática para engenharia',
                'credits' => 6,
                'education_level' => 'Universitário',
                'grade_level' => '1º Ano',
                'semester' => 1,
                'is_mandatory' => true,
                'prerequisites' => '[]',
                'created_at' => now(),
            ],
            [
                'name' => 'Programação I',
                'code' => 'PRG101',
                'description' => 'Introdução à programação',
                'credits' => 6,
                'education_level' => 'Universitário',
                'grade_level' => '1º Ano',
                'course_id' => 1,
                'semester' => 1,
                'is_mandatory' => true,
                'prerequisites' => '[]',
                'created_at' => now(),
            ],
            [
                'name' => 'Física I',
                'code' => 'FIS101',
                'description' => 'Mecânica clássica',
                'credits' => 6,
                'education_level' => 'Universitário',
                'grade_level' => '1º Ano',
                'course_id' => 1,
                'semester' => 1,
                'is_mandatory' => true,
                'prerequisites' => '[]',
                'created_at' => now(),
            ],
            // Disciplinas Universitárias - Medicina (sem pré-requisitos)
            [
                'name' => 'Anatomia Humana I',
                'code' => 'ANA101',
                'description' => 'Estudo da anatomia do corpo humano',
                'credits' => 8,
                'education_level' => 'Universitário',
                'grade_level' => '1º Ano',
                'course_id' => 2,
                'semester' => 1,
                'is_mandatory' => true,
                'prerequisites' => '[]',
                'created_at' => now(),
            ],
            // Disciplinas do Ensino Médio (sem pré-requisitos)
            [
                'name' => 'Matemática',
                'code' => 'MAT10',
                'description' => 'Matemática para 10ª classe',
                'credits' => 4,
                'education_level' => 'Ensino Médio',
                'grade_level' => '10ª Classe',
                'course_id' => null,
                'semester' => null,
                'is_mandatory' => true,
                'prerequisites' => '[]',
                'created_at' => now(),
            ],
            [
                'name' => 'Física',
                'code' => 'FIS10',
                'description' => 'Física para 10ª classe',
                'credits' => 3,
                'education_level' => 'Ensino Médio',
                'grade_level' => '10ª Classe',
                'course_id' => null,
                'semester' => null,
                'is_mandatory' => true,
                'prerequisites' => '[]',
                'created_at' => now(),
            ],
            [
                'name' => 'Química',
                'code' => 'QUI10',
                'description' => 'Química para 10ª classe',
                'credits' => 3,
                'education_level' => 'Ensino Médio',
                'grade_level' => '10ª Classe',
                'course_id' => null,
                'semester' => null,
                'is_mandatory' => true,
                'prerequisites' => '[]',
                'created_at' => now(),
            ],
            [
                'name' => 'História',
                'code' => 'HIS10',
                'description' => 'História de Angola',
                'credits' => 2,
                'education_level' => 'Ensino Médio',
                'grade_level' => '10ª Classe',
                'course_id' => null,
                'semester' => null,
                'is_mandatory' => true,
                'prerequisites' => '[]',
                'created_at' => now(),
            ],
            [
                'name' => 'Geografia',
                'code' => 'GEO10',
                'description' => 'Geografia de Angola',
                'credits' => 2,
                'education_level' => 'Ensino Médio',
                'grade_level' => '10ª Classe',
                'course_id' => null,
                'semester' => null,
                'is_mandatory' => true,
                'prerequisites' => '[]',
                'created_at' => now(),
            ],
            [
                'name' => 'Português',
                'code' => 'POR10',
                'description' => 'Língua Portuguesa',
                'credits' => 4,
                'education_level' => 'Ensino Médio',
                'grade_level' => '10ª Classe',
                'course_id' => null,
                'semester' => null,
                'is_mandatory' => true,
                'prerequisites' => '[]',
                'created_at' => now(),
            ],
            // Disciplinas do Ensino Primário (sem pré-requisitos)
            [
                'name' => 'Matemática',
                'code' => 'MAT1',
                'description' => 'Matemática para 1ª classe',
                'credits' => 4,
                'education_level' => 'Ensino Primário',
                'grade_level' => '1ª Classe',
                'course_id' => null,
                'semester' => null,
                'is_mandatory' => true,
                'prerequisites' => '[]',
                'created_at' => now(),
            ],
            [
                'name' => 'Português',
                'code' => 'POR1',
                'description' => 'Língua Portuguesa para 1ª classe',
                'credits' => 4,
                'education_level' => 'Ensino Primário',
                'grade_level' => '1ª Classe',
                'course_id' => null,
                'semester' => null,
                'is_mandatory' => true,
                'prerequisites' => '[]',
                'created_at' => now(),
            ],
            [
                'name' => 'Estudo do Meio',
                'code' => 'EM1',
                'description' => 'Conhecimento do mundo',
                'credits' => 3,
                'education_level' => 'Ensino Primário',
                'grade_level' => '1ª Classe',
                'course_id' => null,
                'semester' => null,
                'is_mandatory' => true,
                'prerequisites' => '[]',
                'created_at' => now(),
            ],
        ]);

        // Inserir disciplinas com pré-requisitos
        DB::table('subjects')->insert([
            // Disciplinas Universitárias - Engenharia Informática (com pré-requisitos)
            [
                'name' => 'Matemática II',
                'code' => 'MAT102',
                'description' => 'Cálculo diferencial e integral',
                'credits' => 6,
                'education_level' => 'Universitário',
                'grade_level' => '1º Ano',
                'course_id' => 1,
                'semester' => 2,
                'is_mandatory' => true,
                'prerequisites' => '["MAT101"]',
                'created_at' => now(),
            ],
            [
                'name' => 'Programação II',
                'code' => 'PRG102',
                'description' => 'Programação orientada a objetos',
                'credits' => 6,
                'education_level' => 'Universitário',
                'grade_level' => '1º Ano',
                'course_id' => 1,
                'semester' => 2,
                'is_mandatory' => true,
                'prerequisites' => '["PRG101"]',
                'created_at' => now(),
            ],
            [
                'name' => 'Estruturas de Dados',
                'code' => 'EDA201',
                'description' => 'Algoritmos e estruturas de dados',
                'credits' => 6,
                'education_level' => 'Universitário',
                'grade_level' => '2º Ano',
                'course_id' => 1,
                'semester' => 1,
                'is_mandatory' => true,
                'prerequisites' => '["PRG102"]',
                'created_at' => now(),
            ],
            [
                'name' => 'Base de Dados',
                'code' => 'BD201',
                'description' => 'Sistemas de gestão de base de dados',
                'credits' => 6,
                'education_level' => 'Universitário',
                'grade_level' => '2º Ano',
                'course_id' => 1,
                'semester' => 2,
                'is_mandatory' => true,
                'prerequisites' => '["EDA201"]',
                'created_at' => now(),
            ],
            // Disciplinas Universitárias - Medicina (com pré-requisitos)
            [
                'name' => 'Fisiologia I',
                'code' => 'FIS101M',
                'description' => 'Funcionamento dos sistemas corporais',
                'credits' => 8,
                'education_level' => 'Universitário',
                'grade_level' => '1º Ano',
                'course_id' => 2,
                'semester' => 2,
                'is_mandatory' => true,
                'prerequisites' => '["ANA101"]',
                'created_at' => now(),
            ],
            [
                'name' => 'Patologia Geral',
                'code' => 'PAT201',
                'description' => 'Estudo das doenças',
                'credits' => 8,
                'education_level' => 'Universitário',
                'grade_level' => '2º Ano',
                'course_id' => 2,
                'semester' => 1,
                'is_mandatory' => true,
                'prerequisites' => '["FIS101M"]',
                'created_at' => now(),
            ],
            // Disciplinas do Ensino Médio (com pré-requisitos)
            [
                'name' => 'Matemática',
                'code' => 'MAT11',
                'description' => 'Matemática para 11ª classe',
                'credits' => 4,
                'education_level' => 'Ensino Médio',
                'grade_level' => '11ª Classe',
                'course_id' => null,
                'semester' => null,
                'is_mandatory' => true,
                'prerequisites' => '["MAT10"]',
                'created_at' => now(),
            ],
            [
                'name' => 'Matemática',
                'code' => 'MAT12',
                'description' => 'Matemática para 12ª classe',
                'credits' => 4,
                'education_level' => 'Ensino Médio',
                'grade_level' => '12ª Classe',
                'course_id' => null,
                'semester' => null,
                'is_mandatory' => true,
                'prerequisites' => '["MAT11"]',
                'created_at' => now(),
            ],
            // Disciplinas do Ensino Primário (com pré-requisitos)
            [
                'name' => 'Matemática',
                'code' => 'MAT2',
                'description' => 'Matemática para 2ª classe',
                'credits' => 4,
                'education_level' => 'Ensino Primário',
                'grade_level' => '2ª Classe',
                'course_id' => null,
                'semester' => null,
                'is_mandatory' => true,
                'prerequisites' => '["MAT1"]',
                'created_at' => now(),
            ],
            [
                'name' => 'Português',
                'code' => 'POR2',
                'description' => 'Língua Portuguesa para 2ª classe',
                'credits' => 4,
                'education_level' => 'Ensino Primário',
                'grade_level' => '2ª Classe',
                'course_id' => null,
                'semester' => null,
                'is_mandatory' => true,
                'prerequisites' => '["POR1"]',
                'created_at' => now(),
            ],
            [
                'name' => 'Matemática',
                'code' => 'MAT3',
                'description' => 'Matemática para 3ª classe',
                'credits' => 4,
                'education_level' => 'Ensino Primário',
                'grade_level' => '3ª Classe',
                'course_id' => null,
                'semester' => null,
                'is_mandatory' => true,
                'prerequisites' => '["MAT2"]',
                'created_at' => now(),
            ],
            [
                'name' => 'Português',
                'code' => 'POR3',
                'description' => 'Língua Portuguesa para 3ª classe',
                'credits' => 4,
                'education_level' => 'Ensino Primário',
                'grade_level' => '3ª Classe',
                'course_id' => null,
                'semester' => null,
                'is_mandatory' => true,
                'prerequisites' => '["POR2"]',
                'created_at' => now(),
            ],
        ]);

        // 8. Turmas (classes)
        // 8. Turmas (classes)
        DB::table('classes')->insert([
            [
                'name' => 'Matemática I - Turma A',
                'code' => 'MAT101A',
                'subject_id' => 1,
                'education_level' => 'Universitário',
                'grade_level' => '1º Ano',
                'section' => 'A',
                'school_id' => 1,
                'academic_year' => '2024-2025',
                'semester' => 1,
                'max_students' => 40,
                'coordinator_id' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'Programação I - Turma A',
                'code' => 'PRG101A',
                'subject_id' => 2,
                'education_level' => 'Universitário',
                'grade_level' => '1º Ano',
                'section' => 'A',
                'school_id' => 1,
                'academic_year' => '2024-2025',
                'semester' => 1,
                'max_students' => 35,
                'coordinator_id' => 4,
                'created_at' => now(),
            ],
            [
                'name' => 'Anatomia Humana I - Turma A',
                'code' => 'ANA101A',
                'subject_id' => 8,
                'education_level' => 'Universitário',
                'grade_level' => '1º Ano',
                'section' => 'A',
                'school_id' => 2,
                'academic_year' => '2024-2025',
                'semester' => 1,
                'max_students' => 30,
                'coordinator_id' => 2,
                'created_at' => now(),
            ],
            [
                'name' => 'Matemática 10ª - Turma A',
                'code' => 'MAT10A',
                'subject_id' => 11,
                'education_level' => 'Ensino Médio',
                'grade_level' => '10ª Classe',
                'section' => 'A',
                'school_id' => 5,
                'academic_year' => '2024-2025',
                'semester' => null,
                'max_students' => 35,
                'coordinator_id' => 3,
                'created_at' => now(),
            ],
            [
                'name' => 'Matemática 3ª - Turma B',
                'code' => 'MAT3B',
                'subject_id' => 20,
                'education_level' => 'Ensino Primário',
                'grade_level' => '3ª Classe',
                'section' => 'B',
                'school_id' => 8,
                'academic_year' => '2024-2025',
                'semester' => null,
                'max_students' => 25,
                'coordinator_id' => 3,
                'created_at' => now(),
            ],
        ]);

        // 9. Atribuições de Professores (teacher_classes)
        DB::table('teacher_classes')->insert([
            [
                'teacher_id' => 1,
                'class_id' => 1,
                'role' => 'instructor',
                'academic_year' => '2024-2025',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'teacher_id' => 4,
                'class_id' => 2,
                'role' => 'instructor',
                'academic_year' => '2024-2025',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'teacher_id' => 2,
                'class_id' => 3,
                'role' => 'instructor',
                'academic_year' => '2024-2025',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'teacher_id' => 3,
                'class_id' => 4,
                'role' => 'instructor',
                'academic_year' => '2024-2025',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'teacher_id' => 3,
                'class_id' => 5,
                'role' => 'instructor',
                'academic_year' => '2024-2025',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
        ]);

        // 10. Matrículas (class_enrollments)
        DB::table('class_enrollments')->insert([
            [
                'student_id' => 1,
                'class_id' => 1,
                'enrollment_date' => '2024-02-01',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'student_id' => 1,
                'class_id' => 2,
                'enrollment_date' => '2024-02-01',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'student_id' => 2,
                'class_id' => 1,
                'enrollment_date' => '2024-02-01',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'student_id' => 2,
                'class_id' => 2,
                'enrollment_date' => '2024-02-01',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'student_id' => 3,
                'class_id' => 3,
                'enrollment_date' => '2024-02-01',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'student_id' => 4,
                'class_id' => 3,
                'enrollment_date' => '2024-02-01',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'student_id' => 5,
                'class_id' => 4,
                'enrollment_date' => '2024-02-01',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'student_id' => 6,
                'class_id' => 4,
                'enrollment_date' => '2024-02-01',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'student_id' => 7,
                'class_id' => 4,
                'enrollment_date' => '2024-02-01',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'student_id' => 8,
                'class_id' => 5,
                'enrollment_date' => '2024-02-01',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'student_id' => 9,
                'class_id' => 5,
                'enrollment_date' => '2024-02-01',
                'status' => 'active',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
        ]);

        // 11. Solicitações de Matrícula (enrollment_requests)
        DB::table('enrollment_requests')->insert([
            [
                'student_id' => 1,
                'class_id' => 3,
                'reason' => 'Preciso desta disciplina para completar os créditos obrigatórios do meu curso.',
                'status' => 'pending',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'student_id' => 2,
                'class_id' => 3,
                'reason' => 'Disciplina essencial para minha especialização.',
                'status' => 'approved',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'student_id' => 3,
                'class_id' => 1,
                'reason' => 'Quero reforçar meus conhecimentos em matemática.',
                'status' => 'pending',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
        ]);

        // 12. Categorias do Fórum (forum_categories)
        DB::table('forum_categories')->insert([
            [
                'name' => 'Geral',
                'description' => 'Discussões gerais sobre educação',
                'is_global' => true,
                'school_id' => null,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'name' => 'Suporte Técnico',
                'description' => 'Ajuda com problemas técnicos',
                'is_global' => true,
                'school_id' => null,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'name' => 'Anúncios',
                'description' => 'Comunicados oficiais',
                'is_global' => true,
                'school_id' => null,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'name' => 'Matemática',
                'description' => 'Discussões sobre matemática',
                'is_global' => false,
                'school_id' => 1,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'name' => 'Medicina',
                'description' => 'Discussões sobre medicina',
                'is_global' => false,
                'school_id' => 2,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'name' => 'Informática',
                'description' => 'Discussões sobre informática',
                'is_global' => false,
                'school_id' => 1,
                'created_at' => now(),
                //'updated_at' => now(),
            ],
        ]);

        // 13. Configurações do Sistema (system_settings)
        DB::table('system_settings')->insert([
            [
                'setting_key' => 'site_name',
                'setting_value' => 'EduAngola',
                'description' => 'Nome da plataforma',
                'category' => 'general',
                'data_type' => 'string',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'setting_key' => 'academic_year',
                'setting_value' => '2024-2025',
                'description' => 'Ano letivo atual',
                'category' => 'academic',
                'data_type' => 'string',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'setting_key' => 'max_file_size',
                'setting_value' => '10485760',
                'description' => 'Tamanho máximo de arquivo em bytes (10MB)',
                'category' => 'Uploads',
                'data_type' => 'number',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'setting_key' => 'notification_email',
                'setting_value' => 'noreply@eduangola.ao',
                'description' => 'Email para notificações do sistema',
                'category' => 'email',
                'data_type' => 'string',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'setting_key' => 'maintenance_mode',
                'setting_value' => 'false',
                'description' => 'Modo de manutenção',
                'category' => 'system',
                'data_type' => 'boolean',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'setting_key' => 'enrollment_period_start',
                'setting_value' => '2024-01-15',
                'description' => 'Início do período de matrículas',
                'category' => 'academic',
                'data_type' => 'string',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'setting_key' => 'enrollment_period_end',
                'setting_value' => '2024-02-15',
                'description' => 'Fim do período de matrículas',
                'category' => 'academic',
                'data_type' => 'string',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
            [
                'setting_key' => 'grade_scale',
                'setting_value' => '{"A": 18, "B": 16, "C": 14, "D": 12, "F": 10}',
                'description' => 'Escala de notas',
                'category' => 'academic',
                'data_type' => 'json',
                'created_at' => now(),
                //'updated_at' => now(),
            ],
        ]);

        // 14. Audit Logs (usando factory para dados de exemplo)
        AuditLog::factory()->count(10)->create();
    }
}
